blogs/urls.py
from django.urls import path
from blogs.views import BlogPostListView, MyBlogListView, SubcribedBlogsListView, mark_as_read_button, \
    BlogPostCreateView

app_name = 'blogs'
urlpatterns = [
    path('', BlogPostListView.as_view(), name='blogs'),
    path('<pk>/', MyBlogListView.as_view(), name='my-blog'),
    path('subscribed-blog-posts', SubcribedBlogsListView.as_view(), name='subscribed-blogs'),
    path('change_readed', mark_as_read_button, name='mark_as_read'),
    path('post-create', BlogPostCreateView.as_view(), name='post-create'),
]

nikidaemTestProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace="profiles")),
    path('blogs/', include('blogs.urls', namespace="blogs")),
]

profiles/urls.py
from django.urls import path
from profiles.views import ProfileListView, ProfileDetailView, profile_subscribe_button


app_name = 'profiles'
urlpatterns = [
    path('', ProfileListView.as_view(), name='profiles'),
    path('change_subscribe', profile_subscribe_button, name='profile_subscribe'),
    path('<pk>/', ProfileDetailView.as_view(), name='profile-detail'),
]

blogs/models.py
from django.db import models
from profiles.models import Profile


class BlogPost(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post_title = models.CharField("Post Title", max_length=150, unique=True)
    post_content = models.TextField("Content")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post_title

    class Meta:
        ordering = ("-created",)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    subscribed = models.ManyToManyField(User, related_name='subscribed', blank=True)
    readed = models.ManyToManyField("blogs.BlogPost", related_name='readed', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        ordering = ("-created",)

blogs/views.py
from itertools import chain
from django.contrib import messages
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView
from blogs.models import BlogPost
from profiles.models import Profile
from django.contrib.sites.models import Site


class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'blogs/index.html'
    context_object_name = "blogs"
    ordering = "-created"


class MyBlogListView(ListView):
    model = BlogPost
    template_name = 'blogs/my_blog.html'
    context_object_name = "myblog"
    ordering = "-created"

    def get_queryset(self):
        return BlogPost.objects.filter(author__user=self.request.user)


class SubcribedBlogsListView(ListView):
    model = BlogPost
    template_name = 'blogs/subcribed_blogs.html'
    context_object_name = "posts"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        users = [user for user in profile.subscribed.all()]
        posts = []
        for u in users:
            p = Profile.objects.get(user=u)
            p_posts = p.blogpost_set.all()
            posts.append(p_posts)
            unpack = sorted(chain(*posts), reverse=True, key=lambda obj: obj.created)
            context["posts"] = unpack
        readed = profile.readed.all()
        context["readed"] = readed
        return context


@receiver(post_save, sender=BlogPost)
def send_mail_to_subs(sender, instance, created, **kwargs):
    current_site = Site.objects.get_current()
    domain = current_site.domain
    if created:
        for subs in instance.author.subscribed.all():
            send_mail(
                f'New Post from {instance.author}',
                f'Title: {instance.post_title}\nContent: {instance.post_content}\nDate Created: {instance.created}\nUrl: {domain}',
                'testcod77@gmail.com',
                [subs.email],
            )


class BlogPostCreateView(CreateView):
    model = BlogPost
    template_name = 'blogs/post_create.html'
    fields = ["post_title", "post_content"]
    error_message = 'Error saving the post, check fields.'

    def get_success_url(self):
        return reverse("blogs:post-create")

    def form_valid(self, form):
        post_form = form.save(commit=False)
        user = Profile.objects.get(user=self.request.user)
        form.instance.author = user
        post_form.save()
        return super(BlogPostCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, self.error_message)
        return super().form_invalid(form)


def mark_as_read_button(request):
    if request.method == "POST":
        my_profile = Profile.objects.get(user=request.user)
        post = request.POST.get("post_pk")
        obj = BlogPost.objects.get(pk=post)

        if obj in my_profile.readed.all():
            my_profile.readed.remove(obj)
        else:
            my_profile.readed.add(obj)
        return redirect(request.META.get("HTTP_REFERER"))
    return redirect("blogs:subscribed-blogs")

profiles/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from blogs.models import BlogPost
from .models import Profile


class ProfileListView(ListView):
    model = Profile
    template_name = "profiles/index.html"
    context_object_name = "profiles"

    def get_queryset(self):
        return Profile.objects.all().exclude(user=self.request.user)


class ProfileDetailView(DetailView):
    model = Profile
    template_name = "profiles/profile_detail.html"
    context_object_name = "profile"

    def get_object(self, **kwargs):
        pk = self.kwargs.get("pk")
        view_profile = Profile.objects.get(pk=pk)
        return view_profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        view_profile = self.get_object()
        my_profile = Profile.objects.get(user=self.request.user)
        if view_profile.user in my_profile.subscribed.all():
            subscribe = True
        else:
            subscribe = False
        context["subscribe"] = subscribe
        context["profile_posts"] = BlogPost.objects.filter(author__user=view_profile.user)
        return context


def profile_subscribe_button(request):
    if request.method == "POST":
        my_profile = Profile.objects.get(user=request.user)
        pk = request.POST.get("profile_pk")
        obj = Profile.objects.get(pk=pk)

        view_profile = obj.pk
        post_obj = BlogPost.objects.filter(author=view_profile)

        if obj.user in my_profile.subscribed.all():
            my_profile.subscribed.remove(obj.user)
            for r in post_obj:
                my_profile.readed.remove(r.pk)
        else:
            my_profile.subscribed.add(obj.user)
        return redirect(request.META.get("HTTP_REFERER"))
    return redirect("profiles:profile-detail")

blogs/templates/blogs/index.html
{% extends 'base.html' %}

{% block title %}All Blog Posts{% endblock %}

{% block content %}
    {% for post in blogs %}
        <h5 class="card-title">{{ post.post_title }}</h5>
        <p class="card-text">{{ post.created }}</p>
        <p class="card-body">{{ post.post_content }}</p>
        <hr>
    {% endfor %}
{% endblock %}

blogs/templates/blogs/my_blog.html
{% extends 'base.html' %}

{% block title %}My Blog{% endblock %}

{% block content %}
    {% for post in myblog %}
        <h5 class="card-title">{{ post.post_title }}</h5>
        <p class="card-text">{{ post.created }}</p>
        <p class="card-body">{{ post.post_content }}</p>
        <hr>
    {% endfor %}
{% endblock %}

blogs/templates/blogs/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Add a Blog Post{% endblock %}

{% block content %}
    <form action="{% url "blogs:post-create" %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input type="submit" value="Create" class="btn btn-success btn-sm"/>
    </form>
{% endblock %}

blogs/templates/blogs/subcribed_blogs.html
{% extends 'base.html' %}

{% block title %}Subscribed Blog Posts{% endblock %}

{% block content %}
    {% for post in posts %}
        <h5 class="card-title">{{ post.post_title }}</h5>
        {% if post in readed %}
            <form action="{% url "blogs:mark_as_read" %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="post_pk" value={{ post.pk }}>
                <button type="submit" class="btn btn-danger btn-sm">Mark as unread</button>
            </form>
        {% else %}
            <form action="{% url "blogs:mark_as_read" %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="post_pk" value={{ post.pk }}>
                <button type="submit" class="btn btn-success btn-sm">Mark as read</button>
            </form>
        {% endif %}
        <p class="card-text">{{ post.created }}</p>
        <p class="card-body">{{ post.post_content }}</p>
        <hr>
    {% endfor %}
{% endblock %}

profiles/templates/profiles/index.html
{% extends 'base.html' %}

{% block title %}Profile List{% endblock %}

{% block content %}
    {% for profile in profiles %}
        <h5 class="card-title">{{ profile }}</h5>
        <a href="{% url "profiles:profile-detail" profile.pk %}" class="btn btn-primary btn-sm">View Profile</a>
        <hr>
    {% endfor %}
{% endblock %}

profiles/templates/profiles/profile_detail.html
{% extends 'base.html' %}

{% block title %}{{ profile.user }}{% endblock %}

{% block content %}
    <h5 class="card-title">{{ profile.user }}</h5>
    {% if subscribe == True %}
        <form action="{% url "profiles:profile_subscribe" %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value={{ object.pk }}>
            <button type="submit" class="btn btn-danger btn-sm">Unsubscribe</button>
        </form>
    {% else %}
        <form action="{% url "profiles:profile_subscribe" %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="profile_pk" value={{ object.pk }}>
            <button type="submit" class="btn btn-success btn-sm">Subscribe</button>
        </form>
    {% endif %}
    <hr>
    {% for post in profile_posts %}
        <h5 class="card-title">{{ post.post_title }}</h5>
        <p class="card-text">{{ post.created }}</p>
        <p class="card-body">{{ post.post_content }}</p>
        <hr>
    {% endfor %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <br>
        <div class="container">
            <div class="row justify-content-md-center">
                <div class="card col-6 text-center">
                    <div class="card-body">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
                <div class="list-group col-3">
                    <ul>
                        <li class="list-group-item list-group-item-secondary" aria-current="true">Welcome {{ request.user }}</li>
                        <li class="list-group-item list-group-item-action"><a href="{% url "profiles:profiles" %}">Profile List</a></li>
                        <li class="list-group-item list-group-item-action"><a href="{% url "blogs:blogs" %}">All Blog Posts</a></li>
                        <li class="list-group-item list-group-item-action"><a href="{% url "blogs:post-create" %}">Add a Blog Post</a></li>
                        <li class="list-group-item list-group-item-action"><a href="{% url "blogs:my-blog" user.pk %}">My Blog</a></li>
                        <li class="list-group-item list-group-item-action"><a href="{% url "blogs:subscribed-blogs" %}">Subscribed Blogs</a></li>
                    </ul>
                </div>
            </div>
        </div>

        {% block scripts %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        {% endblock %}

    </body>
</html>